### ISSUE TITLE
Context menus appearing after switching tabs

### ISSUE THREAD

**Issue by nrbrt** [bartbutenaers/node-red-contrib-ui-contextmenu#25] opened 2020-04-16 13:18 UTC
I am having an issue with the context menus appearing when I have switched to a different Node-RED tab and return to the tab with the SVG on it. It only shows the context menus that I have had open before switching tabs. So, if I don't open any tabs after restarting Node-RED, no context menus appear.

I use Node-RED v1.0.3 and the latest version of your module: v1.0.11 and my node.js version is v12.16.2

**Comment by bartbutenaers** [comment] 2020-04-17 20:07
Hi @nrbrt ,
Thanks for reporting this one!
I have been able to reproduce the problem, and I have created a new [discussion ](https://discourse.nodered.org/t/msg-replayed-in-ui-node-after-a-tab-switch/25032)on the Node-RED forum about this.  I'm afraid the dashboard code will need to be fixed, to get this solved...
Hopefully Thierry can assist us with this.
Bart

**Comment by bartbutenaers** [comment] 2020-05-01 05:59
Hi @nrbrt,

Seems there are two problems:
+ old div-elements are [not ](https://github.com/bartbutenaers/node-red-contrib-ui-contextmenu/issues/26) cleaned up.  That is easy to solve.
+ for some reason the Node-RED dashboard keeps replaying the old message:
   ![image](https://user-images.githubusercontent.com/14224149/80785638-3d143d00-8b81-11ea-907c-2d29bafdfa34.png)
   I never arrive at my breakpoints on the server-side (where Thierry has fixed this), so it seems to be a client-side issue (in the browser).  Don't know yet how to solve this ...

**Comment by bartbutenaers** [comment] 2020-05-01 19:52
Fixed in version 1.0.12

**Closed as completed by bartbutenaers** 2020-05-01 19:52 UTC
Labels: bug
